### ISSUE TITLE
dead link on Wiki:Pro simplicity papers

### ISSUE THREAD

**Issue by btreut** [congdm/AyaCompiler#12]
The link pointing to http://smirt23.uk/attachments/SMiRT-23_Paper_103.pdf died.

**Comment by congdm** [comment]
Thanks, I've found a new link and update it.
https://repository.lib.ncsu.edu/bitstream/handle/1840.20/33922/SMiRT-23_Paper_103.pdf?sequence=1&isAllowed=y
