### ISSUE TITLE
please enhance with union tag

### ISSUE THREAD

**Issue by r-k-o** [congdm/AyaCompiler#8]
hi,
since the compiler runs on windows, please reconsider to bring a union tag such as in blackbox or any other way.  
porting the win32 abi is a pain in the kister without it.

**Comment by congdm** [comment]
At the current time, there are many other problems that need to be addressed until the compiler is stable enough, so I think UNION feature can wait.

**Comment by r-k-o** [comment]
hi, thanx for implementing this. trying to work with now.
